apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: argocd-app
  template:
    metadata:
      labels:
        app: argocd-app
    spec:
      containers:
      - name: argocd-app
        image: nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: argocd-svc
spec:
  selector:
    app: argocd-app
  ports:
  - port: 80
    targetPort: 80
